# Generated by Django 3.0.8 on 2020-07-13 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.URLField(null=True)),
            ],
            options={
                'db_table': 'social_media',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_account', models.URLField(unique=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('profile_image', models.URLField(max_length=2000, null=True)),
                ('birthdate', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('social_media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.SocialMedia')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
