# Generated by Django 3.0.8 on 2020-07-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='nickname',
        ),
    ]
