# Generated by Django 3.1.2 on 2021-01-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_dog_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='email_account',
            new_name='email',
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
